export const MSG = {
  NEW_RECORD: '新規作成しますか？\nDo you create new sheet?',
  REVUP_SAVE_CONFIRM: 'RevUp保存しますか？\nSave this to new version?',
  REVUP_SAVED: 'RevUp保存しました。\nIt saved by new version',
  SAVE_FAILED: '保存に失敗しました\nFailed to saved.',
  DELETE_RECORD: '削除しますか？\nDelete this sheet?',
  CANNOT_REPORT: '承認者が設定されていないため、上申できません。\nThis data cannot be Report.',
  CANNOT_RECOGNITION: 'このデータは承認できません。\nThis data cannot be Recognition.',
  CANNOT_REJECT: 'このデータは否認できません。\nThis data cannot be Returns to Reviewer.',
  CANNOT_RELATION: '未入力のFactがあるため、紐づけできません。\nRelation not allowed, Because there is fact of non-input.',
  CANNOT_ADD: '追加できません。\nIt cannot add',
  CANNOT_MOVE: '移動できません。\nIt cannot move',
  CANNOT_REPORTED: 'このデータは上申できません。\nThis data cannot be Reported.',
  DELETE_FACT: '2.観察事実の(%(num)s)を削除しますか？\nIs an observation example deleted?',
  DELETE_CONCLUSION: '3.結論の(%(num)s)を削除しますか？\nIs an Conclusion deleted?',
  EMPTY_PASSWORD_FIELD: 'fields can not be empty',
  NOT_MAP_PASSWORD: 'new password and confirm password not map',
  LOGIN_REQUIRED_HEADER: 'Login Required - Use Peer Review No and Three Initials and Password',
  LOGIN_REQUIRED_MSG: 'データベースを使用するには、ログインが必要です。\nUser must login to use the database!',
  VERIFY_LOGIN: 'パスワードを確認し、再度ログインしてください。<br/>Please verify login password, then login again and complete the user information form',
  VERIFY_CONNECT_DESTINATION: '接続先が未入力です。\nConnection destination has not been entered!',
  VERIFY_INITIAL: 'イニシャルを確認し、再度ログインしてください。\nPlease verify login initials\n then login again and complete the user information form ',
  VERIFY_PASSWORD: 'パスワードを確認し、再度ログインしてください。\nPlease verify login password\n then login again and complete the user information form ',
  RELATED_AREA_NOT_FILLED: '提供先分野が未入力の事実があります。\n"Related Area" is not filled in. OK?',
  RELATED_POC_NOT_FILLED: '提供先PO&Cが未入力の事実があります。\n"Related PO&C" is not filled in. OK?',
  DATA_SAVED: '上書き保存しました。\nData was saved.',
  DATA_SAVED_TRANS_REQUEST: '上書き保存しました。翻訳依頼は忘れていませんか？\nData was saved. Have you forgotten your translation request?',
  CANNOT_EDIT: 'このデータは編集できません。\nThis data cannot be edited.',
  REPORT_CONFIRM: '上申してよろしいですか？\nDo you Report?',
  REPORT_WITHOUT_TRANS_REQUEST: '上申してよろしいですか？  翻訳依頼は忘れていませんか？\nDo you Report? Have you forgotten your translation request?',
  GFA_WORD_CREATE: 'フォーカスエリア分析シート一覧をワードファイルにして「Docs in Word」フォルダに保存します。\nRequested files will be saved in "Docs in Word" folder located in FND folder as MS-word file.',
  PFA_WORD_CREATE: 'プラスフォーカスエリア分析シート一覧をワードファイルにして「Docs in Word」フォルダに保存します。\nRequested files will be saved in "Docs in Word" folder located in FND folder as MS-word file.',
  AFI_WORD_CREATE: '要改善事項一覧をワードファイルにして「Docs in Word」フォルダに保存します。\nRequested files will be saved in "Docs in Word" folder located in FND folder as MS-word file.',
  BP_WORD_CREATE: '有益事例一覧をワードファイルにして「Docs in Word」フォルダに保存します。\nRequested files will be saved in "Docs in Word" folder located in FND folder as MS-word file.',
  OBS_WORD_CREATE: '観察シート一覧をワードファイルにして「Docs in Word」フォルダに保存します。\nRequested files will be saved in "Docs in Word" folder located in FND folder as MS-word file.',
  PD_WORD_CREATE: '軽微な問題点一覧をワードファイルにして「Docs in Word」フォルダに保存します。\nRequested files will be saved in "Docs in Word" folder located in FND folder as MS-word file.',
  STR_WORD_CREATE: '良好事例一覧をワードファイルにして「Docs in Word」フォルダに保存します。\nRequested files will be saved in "Docs in Word" folder located in FND folder as MS-word file.',
  SOI_WORD_CREATE: '改善状況評価シート一覧をワードファイルにして「Docs in Word」フォルダに保存します。\nRequested files will be saved in "Docs in Word" folder located in FND folder as MS-word file.',
  ERROR_IN_PROCESS: '処理中にエラーが発生しました。/The error occurred during processing.',
  ERROR_IN_PROCESS_FULL_ERROR: '処理中にエラーが発生しました。調整員に連絡してください。\nThe error occurred during processing. Please contact coordinator.',
  DATA_CHANGED: '内容が変更されています。適用しないで閉じますか？\nData was changed, Does it close without applying?',
  DELETE_PHOTO: '写真を削除しますか？\nIs a photograph deleted?',
  OPEN_TRANSLATE_FORM: '選択したシートの翻訳が完了しています。翻訳管理メニューを開きますか？\nTranslation of the selected sheet is complete. Open the translation management menu?',
  NO_DATA: 'データが見つかりません。処理を中止します。\nIt no data. Stop the process.',
  CANNOT_ACCESS_PLANT_NAME: 'メンバ登録されていないためレビュー先にアクセスできません。\n Cannot access, because It isn\'t registered as a member..',
  ERR_MSG_WORDFOLDER: '・Wordファイルの保管先フォルダが設定されていません。\n',
  ERR_MSG_PHOTOLIVE: '・写真(ライブデータ)の保管先フォルダが設定されていません。\n',
  ERR_MSG_PHOTOPAST: '・写真(過去データ)の保管先フォルダが設定されていません。\n',
  ERR_MSG_DOC_PUT_TRANS: '・翻訳の出力先フォルダが設定されていません。\n',
  ERR_MSG_DOC_IN_TRANS: '・翻訳の取込先フォルダが設定されていません。\n',
  ERR_MSG_DOC_IN_TRANS_FIN: '・翻訳の取込先翻訳済フォルダが設定されていません。\n',
  ERR_REQUIRED_CONTACT: '調整員に連絡してください。 \nThe save destination folder is not set. Please contact coordinator.',
  ERR_REQUIRED_TRANS_RANGE: '翻訳範囲を選択してください。" & vbCrLf & "Please choose the translation range.',
  ERR_REQUIRED_TRANS_ITEM: '部分翻訳する項目が指定されていません。" & vbCrLf & "Please check the translation item.',
  ERR_OUTPUT_MS_WORD_NOT_FOUND: '同期先または翻訳Word出力先が見つからないため処理できません。/Cannot be processed because a Synchronize Path or Output MS-Word Path isn\'t found.',
  ERR_TRANS_CANCELED: '翻訳依頼を解除しますか？\nIs a translation request canceled?',
  TRANS_TITLE: '翻訳依頼（保存、翻訳Word出力）しますか？\n（翻訳が完了するまでシートは編集できなくなります）\nDo you request translation (Sheet Saved, Translation MS-Word output) ?\n(You will NOT be able to modify sheet until completion of the translation work.)\n◆Word出力先 MS-Word Path',
  ERR_REQUIRED_RECOGZER: '希望期限を選択してください。/Please choose an Recognizer ',
  ERR_OFFLINE: 'オフラインになったため処理できません。/Cannot be processed offline.',
  TRANS_CONFIRM_PRINT: '%(plantName)s-%(num)s  は出力済です。再出力しますか？\n%(plantName)s-%(num)s is outputed. Do you the it output?',
  NOT_HAVE_EDIT_PERMISION: 'このシートは編集権限がないため、上申できません。\nThis sheet is not have edit permissions for the cannot be reported.',
  PHOTO_FORMAT_INCORRECT: '写真の形式が正しくありません \nPhoto format is incorrect.',
  ERR_MSG_INPUT_VALID: '入力値が並び替え数より大きいです \n Input value is greater than sort number。',
};

export const MODAL = {
  YES: 'はい(Y)',
  NO: 'いいえ(N)',
  CANCEL: 'キャンセル(Cancel)',
  OK: 'OK',
  TITLE_INFO: 'Information',
  TITLE_WARNING: 'Warning',
  TITLE_REQUIRED_SYNC: 'Please Synchronize',
};

export const CONFIRM_DIALOG = {
  YES: 'confirm_yes',
  NO: 'confirm_no',
  DENY: 'confirm_deny',
  CONTENT_NO: 'dlgContent_no',

};

export const LANGUAGE = {
  JAPAN_FIRST_LETTER: 'J',
  ENGLISH_FIRST_LETTER: 'E',
  JAPAN_CODE: 'ja-JP',
  ENGLISH_CODE: 'en-US',
  ENGLISH_ID: 2,
  JAPAN_ID: 1,
  ORIGINAL_ID: 0,
};

export const IMAGE_TYPE_CHECK = 'image';

export const ALT_IMAGE = 'a imported image';
export const TRAN_FULL_TEXT = '全文／Whole';
export const APPROVAL_STATE = {
  JAPAN_CHECK_REQ: '確認依頼',
  ENG_CHECK_REQ: 'Check REQ',
  JAPAN_REPORT: '上申',
  ENG_REPORT: 'Report',
  JAPAN_RETURN_TO_REVIEWER: 'レビューワーに戻す',
  ENG_RETURN_TO_REVIEWER: 'Returns to Reviewer',
  JAPAN_RECOGNITION: '承認',
  ENG_RECOGNITION: 'Recognition',
  JAPAN_RECOGNITION_COMM: '承認（コメント有）',
  ENG_RECOGNITION_COMM: 'Recognition(Comm)',
};
