CREATE TABLE IF NOT EXISTS tenants (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    code character varying(10) NOT NULL,
    name character varying(80) NOT NULL,
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone DEFAULT NOW() NOT NULL,
    updated_at timestamp with time zone DEFAULT NOW() NOT NULL,
    created_by character varying(50) NULL,
    updated_by character varying(50) NULL,
    CONSTRAINT PK_tenants PRIMARY KEY (id),
    CONSTRAINT UNQ_tenants_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS accounts (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    tenant_code character varying(10) NOT NULL,
    code character varying(15) NOT NULL,
    name character varying(80) NOT NULL,
    email character varying(50) NOT NULL,
    password character varying(255) NULL,
    role_kbn character varying(2) NOT NULL DEFAULT '02',
    is_deleted boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone DEFAULT NOW() NOT NULL,
    updated_at timestamp with time zone DEFAULT NOW() NOT NULL,
    created_by character varying(50) NULL,
    updated_by character varying(50) NULL,
    CONSTRAINT PK_accounts PRIMARY KEY (id),
    CONSTRAINT UNQ_accounts_tenant_code_code UNIQUE (tenant_code, code)
);

CREATE INDEX IDX_accounts_email ON accounts (email);